### ISSUE TITLE
Question about chage model

### ISSUE THREAD

**Issue by zzzfo** [FeiGeChuanShu/ncnn-android-yolox#3]
if I want to increase yolox-s in this project,what should I do ??

**Comment by FeiGeChuanShu** [comment]
> if I want to increase yolox-s in this project,what should I do ??
https://github.com/FeiGeChuanShu/ncnn-android-yolox/blob/main/app/src/main/jni/yoloxncnn.cpp#L186
https://github.com/FeiGeChuanShu/ncnn-android-yolox/blob/main/app/src/main/res/values/strings.xml#L5
add your new model in according to this code

**Comment by zzzfo** [comment]
thxs

> > if I want to increase yolox-s in this project,what should I do ??
> > https://github.com/FeiGeChuanShu/ncnn-android-yolox/blob/main/app/src/main/jni/yoloxncnn.cpp#L186
> > https://github.com/FeiGeChuanShu/ncnn-android-yolox/blob/main/app/src/main/res/values/strings.xml#L5
> > add your new model in according to this code
