### ISSUE TITLE
生成的Android demo出现了闪退

### ISSUE THREAD

**Issue by ppogg** [FeiGeChuanShu/ncnn-android-yolox#4]
先生您好,如题,毫无修改的使用您的代码可以成功release出apk包,但是一打开就出现了闪退,请问是什么原因呢?

**Comment by w-x-j00** [comment]
> 好,如题,毫无修改的使用您的代码可以成功release出apk包,但是一打开就出现了闪退,请问是什么原因呢?请问你解决了么？
